-- W1 READ-ONLY. Catalog metadata and aggregate counts only; no individual rows.
SELECT jsonb_build_object(
  'recorded_at', now(),
  'postgres_version', current_setting('server_version'),
  'database', current_database(),
  'schemas', (SELECT jsonb_agg(jsonb_build_object('name',nspname,'owner',pg_get_userbyid(nspowner),'acl',nspacl::text) ORDER BY nspname)
    FROM pg_namespace WHERE nspname IN ('public','rdd_private','invite_private','rivalry_private','supabase_migrations')),
  'relations', (SELECT coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'name',c.relname,'kind',c.relkind,'rls',c.relrowsecurity,'force_rls',c.relforcerowsecurity,'owner',pg_get_userbyid(c.relowner),'options',c.reloptions,'acl',c.relacl::text) ORDER BY n.nspname,c.relname),'[]'::jsonb)
    FROM pg_class c JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN ('public','rdd_private','invite_private','rivalry_private') AND c.relkind IN ('r','p','v','m','S')),
  'columns', (SELECT jsonb_agg(jsonb_build_object('schema',table_schema,'table',table_name,'position',ordinal_position,'name',column_name,'type',data_type,'udt',udt_name,'nullable',is_nullable,'default',column_default) ORDER BY table_schema,table_name,ordinal_position)
    FROM information_schema.columns WHERE table_schema IN ('public','rdd_private','invite_private','rivalry_private')),
  'constraints', (SELECT jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',con.conname,'type',con.contype,'validated',con.convalidated,'definition',pg_get_constraintdef(con.oid)) ORDER BY n.nspname,c.relname,con.conname)
    FROM pg_constraint con JOIN pg_class c ON c.oid=con.conrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE n.nspname IN ('public','rdd_private','invite_private','rivalry_private')),
  'indexes', (SELECT jsonb_agg(jsonb_build_object('schema',schemaname,'table',tablename,'name',indexname,'definition',indexdef) ORDER BY schemaname,tablename,indexname) FROM pg_indexes WHERE schemaname IN ('public','rdd_private','invite_private','rivalry_private')),
  'policies', (SELECT jsonb_agg(jsonb_build_object('schema',schemaname,'table',tablename,'name',policyname,'permissive',permissive,'roles',roles,'command',cmd,'using',qual,'check',with_check) ORDER BY schemaname,tablename,policyname) FROM pg_policies WHERE schemaname IN ('public','rdd_private','invite_private','rivalry_private','auth','storage')),
  'functions', (SELECT coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'name',p.proname,'arguments',pg_get_function_identity_arguments(p.oid),'result',pg_get_function_result(p.oid),'definer',p.prosecdef,'config',p.proconfig,'acl',p.proacl::text,'owner',pg_get_userbyid(p.proowner)) ORDER BY n.nspname,p.proname,p.oid),'[]'::jsonb) FROM pg_proc p JOIN pg_namespace n ON n.oid=p.pronamespace WHERE n.nspname IN ('public','rdd_private','invite_private','rivalry_private')),
  'triggers', (SELECT coalesce(jsonb_agg(jsonb_build_object('schema',n.nspname,'table',c.relname,'name',t.tgname,'definition',pg_get_triggerdef(t.oid),'enabled',t.tgenabled) ORDER BY n.nspname,c.relname,t.tgname),'[]'::jsonb) FROM pg_trigger t JOIN pg_class c ON c.oid=t.tgrelid JOIN pg_namespace n ON n.oid=c.relnamespace WHERE NOT t.tgisinternal AND n.nspname IN ('public','auth','storage','rdd_private','invite_private','rivalry_private')),
  'grants', (SELECT jsonb_agg(jsonb_build_object('schema',table_schema,'table',table_name,'grantee',grantee,'privilege',privilege_type,'grantable',is_grantable) ORDER BY table_schema,table_name,grantee,privilege_type) FROM information_schema.table_privileges WHERE table_schema IN ('public','rdd_private','invite_private','rivalry_private')),
  'column_grants', (SELECT jsonb_agg(jsonb_build_object('schema',table_schema,'table',table_name,'column',column_name,'grantee',grantee,'privilege',privilege_type) ORDER BY table_schema,table_name,column_name,grantee,privilege_type) FROM information_schema.column_privileges WHERE table_schema IN ('public','rdd_private','invite_private','rivalry_private')),
  'sequences', (SELECT jsonb_agg(jsonb_build_object('schema',schemaname,'name',sequencename,'type',data_type::text,'start',start_value::text,'min',min_value::text,'max',max_value::text,'increment',increment_by,'cycle',cycle,'cache',cache_size) ORDER BY schemaname,sequencename) FROM pg_sequences WHERE schemaname='public'),
  'default_grants', (SELECT jsonb_agg(jsonb_build_object('owner',pg_get_userbyid(d.defaclrole),'schema',n.nspname,'object_type',d.defaclobjtype,'acl',d.defaclacl::text) ORDER BY n.nspname,d.defaclobjtype) FROM pg_default_acl d LEFT JOIN pg_namespace n ON n.oid=d.defaclnamespace WHERE n.nspname='public' OR d.defaclnamespace=0),
  'extensions', (SELECT jsonb_agg(jsonb_build_object('name',e.extname,'version',e.extversion,'schema',n.nspname) ORDER BY e.extname) FROM pg_extension e JOIN pg_namespace n ON n.oid=e.extnamespace),
  'client_roles', (SELECT jsonb_agg(jsonb_build_object('name',rolname,'superuser',rolsuper,'bypass_rls',rolbypassrls,'create_role',rolcreaterole,'create_db',rolcreatedb,'inherit',rolinherit) ORDER BY rolname) FROM pg_roles WHERE rolname IN ('anon','authenticated','service_role')),
  'client_role_memberships', (SELECT coalesce(jsonb_agg(jsonb_build_object('role',r.rolname,'member',m.rolname,'admin',a.admin_option)),'[]'::jsonb) FROM pg_auth_members a JOIN pg_roles r ON r.oid=a.roleid JOIN pg_roles m ON m.oid=a.member WHERE m.rolname IN ('anon','authenticated','service_role')),
  'migration_namespace_exists', EXISTS(SELECT 1 FROM pg_namespace WHERE nspname='supabase_migrations'),
  'migration_table_exists', to_regclass('supabase_migrations.schema_migrations') IS NOT NULL,
  'counts', jsonb_build_object('profiles',(SELECT count(*) FROM public.profiles),'matches',(SELECT count(*) FROM public.matches),'participants',(SELECT count(*) FROM public.match_players),'auth_users',(SELECT count(*) FROM auth.users),'storage_buckets',(SELECT count(*) FROM storage.buckets),'storage_objects',(SELECT count(*) FROM storage.objects)),
  'integrity', jsonb_build_object(
    'bad_rosters',(SELECT count(*) FROM (SELECT m.id FROM public.matches m LEFT JOIN public.match_players mp ON mp.match_id=m.id GROUP BY m.id HAVING count(mp.id)<2 OR count(mp.id)>10 OR count(mp.player_id)<>count(mp.id) OR count(DISTINCT mp.player_id)<>count(mp.id) OR count(*) FILTER(WHERE mp.is_winner IS TRUE)<>1 OR count(*) FILTER(WHERE mp.id IS NOT NULL AND mp.is_winner IS NULL)>0) q),
    'orphan_participants',(SELECT count(*) FROM public.match_players mp LEFT JOIN public.matches m ON m.id=mp.match_id LEFT JOIN public.profiles p ON p.id=mp.player_id WHERE m.id IS NULL OR p.id IS NULL),
    'missing_creators',(SELECT count(*) FROM public.matches m LEFT JOIN public.profiles p ON p.id=m.created_by WHERE p.id IS NULL),
    'bad_times',(SELECT count(*) FROM public.matches WHERE played_at IS NULL OR NOT isfinite(played_at) OR played_at>now()+interval '5 minutes'),
    'unsupported_labels',(SELECT count(*) FROM public.matches WHERE game_type IS NULL OR game_type NOT IN ('301','501','Cricket','Other') OR board_type IS NULL OR board_type NOT IN ('Steel Tip','Soft Tip')),
    'bad_summary_values',(SELECT count(*) FROM public.match_players mp JOIN public.matches m ON m.id=mp.match_id WHERE (mp.score IS NOT NULL AND (mp.score::text IN ('NaN','Infinity','-Infinity') OR mp.score<0 OR mp.score>(CASE WHEN m.game_type IN ('301','501') THEN 180 WHEN m.game_type='Cricket' THEN 9 ELSE 9999 END) OR (m.game_type='Other' AND mp.score<>trunc(mp.score)))) OR (mp.points_scored IS NOT NULL AND (mp.points_scored::text IN ('NaN','Infinity','-Infinity') OR mp.points_scored<0 OR mp.points_scored>9999 OR mp.points_scored<>trunc(mp.points_scored) OR m.game_type<>'Cricket')))
  )
) AS w1_catalog;
